<?php if($block->isModuleEnabled()):?>
<script data-cfasync="false" type="text/javascript">
  window.civchat = {
    apiKey: '<?= $block->getApi() ?>',
    name: "John Doe",
    user_id: "idfromyourdatabase",
    email: "myemail@example.org",
    gender: 2,
    status: 2,
    date_attr: "2017-07-25T14:14:08.612Z",   // Must be a valid ISO 8601 format
    phone_number: "+44754123434", // Must be a valid E.164 format
    score: 0,
    company: {
      name: "My Company",
      company_id: "idfromyourdatabase",
      revenue: "$239.9 billion"
    }
  };
</script>
<script data-cfasync="false" type="text/javascript" src="https://<?= $block->getSubdomain() ?>.user.com/widget.js"></script>
<?php endif ?>
